# Generated by Django 4.2.2 on 2023-06-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name="Question",
            old_name="question_test",
            new_name="question_text",
        )
    ]
